// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package collector

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// LoadExecve returns the embedded CollectionSpec for Execve.
func LoadExecve() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_ExecveBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Execve: %w", err)
	}

	return spec, err
}

// LoadExecveObjects loads Execve and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*ExecveObjects
//	*ExecvePrograms
//	*ExecveMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadExecveObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadExecve()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// ExecveSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ExecveSpecs struct {
	ExecveProgramSpecs
	ExecveMapSpecs
	ExecveVariableSpecs
}

// ExecveProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ExecveProgramSpecs struct {
	HandleExecve *ebpf.ProgramSpec `ebpf:"handle_execve"`
}

// ExecveMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ExecveMapSpecs struct {
	Events *ebpf.MapSpec `ebpf:"events"`
}

// ExecveVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ExecveVariableSpecs struct {
}

// ExecveObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadExecveObjects or ebpf.CollectionSpec.LoadAndAssign.
type ExecveObjects struct {
	ExecvePrograms
	ExecveMaps
	ExecveVariables
}

func (o *ExecveObjects) Close() error {
	return _ExecveClose(
		&o.ExecvePrograms,
		&o.ExecveMaps,
	)
}

// ExecveMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadExecveObjects.
type ExecveMaps struct {
	Events *ebpf.Map `ebpf:"events"`
}

func (m *ExecveMaps) Close() error {
	return _ExecveClose(
		m.Events,
	)
}

// ExecveVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadExecveObjects or ebpf.CollectionSpec.LoadAndAssign.
type ExecveVariables struct {
}

// ExecvePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadExecveObjects or ebpf.CollectionSpec.LoadAndAssign.
type ExecvePrograms struct {
	HandleExecve *ebpf.Program `ebpf:"handle_execve"`
}

func (p *ExecvePrograms) Close() error {
	return _ExecveClose(
		p.HandleExecve,
	)
}

func _ExecveClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed execve_bpfel.o
var _ExecveBytes []byte
